name: secondsight
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.34.2
  drift_flutter: ^0.3.1
  path_provider: ^2.1.6
  rxdart: ^0.28.0
  uuid: ^4.5.1
  home_widget: ^0.9.3
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.34.4
  build_runner: ^2.15.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: "#0B0E13"
  adaptive_icon_foreground: assets/icon/icon_fg.png
