name: secondsight
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.34.2
  drift_flutter: ^0.3.1
  path_provider: ^2.1.6
  rxdart: ^0.28.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.34.4
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
